import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
        serif: ["Georgia", "serif"],
      },
      fontSize: {
        display: ["4rem", { lineHeight: "1.1" }],
        "section-heading": ["3.25rem", { lineHeight: "1.2" }],
        "sub-lg": ["2.3rem", { lineHeight: "1.3" }],
        "sub-md": ["2rem", { lineHeight: "1.1" }],
        "sub-sm": ["1.6rem", { lineHeight: "1.2" }],
        "feature-title": ["1.3rem", { lineHeight: "1.2" }],
        "body-lg": ["1.25rem", { lineHeight: "1.6" }],
        "body-ui": ["1.06rem", { lineHeight: "1.6" }],
        caption: ["0.88rem", { lineHeight: "1.43" }],
        label: ["0.75rem", { lineHeight: "1.25" }],
        overline: ["0.63rem", { lineHeight: "1.6" }],
      },
      spacing: {
        "0.5u": "3px",
        "0.75u": "4px",
        "1u": "6px",
        "1.5u": "8px",
        "2u": "10px",
        "2.5u": "12px",
        "3u": "16px",
        "4u": "20px",
        "5u": "24px",
        "6u": "30px",
        "section": "5rem",
        "section-lg": "7.5rem",
      },
      maxWidth: {
        container: "1200px",
      },
      boxShadow: {
        ring: "0px 0px 0px 1px var(--ring-color)",
        "ring-warm": "0px 0px 0px 1px #d1cfc5",
        "ring-dark": "0px 0px 0px 1px #30302e",
        "ring-terracotta": "0px 0px 0px 1px #c96442",
        whisper: "0px 4px 24px rgba(0,0,0,0.05)",
        "whisper-dark": "0px 4px 24px rgba(0,0,0,0.25)",
        "inset-press": "inset 0px 0px 0px 1px rgba(0,0,0,0.15)",
      },
      colors: {
        "near-black": "#141413",
        terracotta: "#c96442",
        coral: "#d97757",
        error: "#b53333",
        focus: "#3898ec",
        parchment: "#f5f4ed",
        ivory: "#faf9f5",
        "warm-sand": "#e8e6dc",
        "dark-surface": "#30302e",
        "charcoal-warm": "#4d4c48",
        "olive-gray": "#5e5d59",
        "stone-gray": "#87867f",
        "dark-warm": "#3d3d3a",
        "warm-silver": "#b0aea5",
        "border-cream": "#f0eee6",
        "border-warm": "#e8e6dc",
        "ring-warm": "#d1cfc5",
        "ring-subtle": "#dedcd1",
        "ring-deep": "#c2c0b6",
        surface: "var(--surface)",
        "surface-elevated": "var(--surface-elevated)",
        page: "var(--page)",
        ink: "var(--ink)",
        "ink-secondary": "var(--ink-secondary)",
        "ink-tertiary": "var(--ink-tertiary)",
        hairline: "var(--ring-color)",
      },
    },
  },
  plugins: [],
};
export default config;
